//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaheAzWebApiAlakbarAlakbarov.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDbEntitiesAnnouncement : DbContext
    {
        public MyDbEntitiesAnnouncement()
            : base("name=MyDbEntitiesAnnouncement")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcement> Announcement { get; set; }
        public virtual DbSet<User> User { get; set; }

        public System.Data.Entity.DbSet<SaheAzWebApiAlakbarAlakbarov.Models.Favourite> Favourites { get; set; }
    }
}
